name: Publish

on:
  release:
    types: [created]

jobs:
  publish-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run mvn deploy
        run: mvn --batch-mode --projects ngrok-java --also-make deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}